// Copyright (c) 2026 Ronan Le Meillat - SCTG Development
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

/**
 * @file reports/report-tools.ts
 *
 * Factory that creates the `generate_report` agent tool.
 *
 * The report tool is the **terminal step** of every sync run: the agent calls it
 * after processing all candidate commits.  Setting `lifecycle: { completesRun: true }`
 * signals to the `@sctg/cline-sdk` runtime that the agent should stop after this
 * tool returns, so the tool doubles as both report generator and run terminator.
 *
 * The tool produces:
 *  - A human-readable **Markdown string** suitable for use as a GitHub PR body.
 *  - A compact **agentState** object that can be embedded in the PR body (hidden
 *    HTML comment) for idempotent re-runs (see `github-tools.ts`).
 *  - Boolean flags `allPassed` and `needsHumanReview` for caller logic.
 *  - A detailed **Markdown file** written to `config.report.destination` combining
 *    the PR-body summary, a Mermaid workflow diagram generated by the fast model,
 *    and a full transcript of every AI sub-agent call from the prompts JSONL log.
 *
 * Report sections (PR body):
 *  1. Header — date, upstream ref, fork ref, sync branch name.
 *  2. Summary — counts of applied / needs-review / blocked commits.
 *  3. Applied commits — listed with risk badges and conflict-resolution notes.
 *  4. Human review required — conflicted or validation-failed commits with reasons.
 *  5. Blocked commits — SHAs that were not attempted at all.
 *  6. Agent decision log — ordered audit trail of key agent decisions.
 *
 * Additional sections (detailed file only):
 *  7. Mermaid workflow diagram — generated by the fast LLM from the run summary.
 *  8. AI sub-agent call log — full prompt/response transcript from the JSONL log.
 */

import { z } from "zod";
import { readFileSync, writeFileSync, mkdirSync, existsSync, unlinkSync } from "node:fs";
import { resolve as resolvePath, join as joinPath, relative as relativePath } from "node:path";
import { git } from "../git/git-client.js";
import { CHECKPOINT_FILENAME } from "../git/git-tools.js";
import { createOrUpdateSyncPr } from "../github/github-tools.js";
import { Agent } from "@sctg/cline-sdk";
import { defineTool } from "../tool-helper.js";
import type { SyncConfig } from "../config/schema.js";
import { validationFailed, validationRan, type RunState } from "../agent/run-state.js";

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

/**
 * Shape of a single prompt-entry in the `.prompts.jsonl` log file.
 * Extended fields (confidence, guards, hallucinationSuspectsCount…) are
 * optional because they were added progressively — older log files may not
 * carry them.
 */
interface PromptLogEntry {
  type?: "prompt" // absent or "prompt" for backward compat
  timestamp: string
  tool: string
  model: string
  durationMs: number
  prompt: string
  response: string
  error?: string
  inputTokens?: number
  outputTokens?: number
  cacheReadTokens?: number
  cacheWriteTokens?: number
  totalCost?: number
  // Quality fields added by the improved ai-tools (Improvement 1 / 5 / 6 / 8)
  originalConfidence?: string
  effectiveConfidence?: string
  hasConflictMarkers?: boolean
  syntaxValid?: boolean
  consensusFailure?: boolean
  guards?: string[]
  recommendation?: string
  backportComplexity?: string
  semanticRiskFactorsCount?: number
  hallucinationSuspectsCount?: number
  compatible?: boolean
  affectedCount?: number
  semanticConflictsCount?: number
  fileContentEnriched?: boolean
}

/**
 * Shape of a structured audit event in the `.prompts.jsonl` log file.
 * Audit events are written unconditionally at the tool layer (Improvement 9).
 */
interface AuditEventEntry {
  type: "audit_event"
  timestamp: string
  tool: string
  event: string
  details?: Record<string, unknown>
}

/** Union of all possible JSONL log record shapes. */
type LogEntry = PromptLogEntry | AuditEventEntry

/**
 * Reads the JSONL prompt log, returning prompt entries and audit events separately.
 * Silently skips malformed lines so a corrupt log cannot block the report.
 */
function readPromptLog(logPath: string): { prompts: PromptLogEntry[]; auditEvents: AuditEventEntry[] } {
  if (!existsSync(logPath)) return { prompts: [], auditEvents: [] }
  try {
    const entries = readFileSync(logPath, "utf8")
      .split("\n")
      .filter(Boolean)
      .flatMap((line) => {
        try {
          return [JSON.parse(line) as LogEntry]
        } catch {
          return []
        }
      })
    return {
      prompts: entries.filter((e): e is PromptLogEntry => e.type !== "audit_event"),
      auditEvents: entries.filter((e): e is AuditEventEntry => e.type === "audit_event"),
    }
  } catch {
    return { prompts: [], auditEvents: [] }
  }
}

// Infer the keypoolEventHandler type from Agent's constructor options.
type KeypoolEventHandler = NonNullable<Parameters<typeof Agent>[0]> extends
  { keypoolEventHandler?: (e: infer E) => void } ? ((e: E) => void) : never

/**
 * Instantiates a minimal sub-Agent with no tools for a single reasoning turn.
 * Identical in purpose to the helper in `ai-tools.ts` but local to avoid a
 * cross-module import cycle.
 *
 * @param modelId             - Model identifier to use for the sub-agent.
 * @param systemPrompt        - System prompt to inject.
 * @param providerId          - Provider identifier (e.g. `"openai"`, `"anthropic"`).
 * @param apiKey              - API key for the provider, or `undefined` if using env-based auth.
 * @param keypoolEventHandler - Optional keypool event handler forwarded from the main agent
 *                              so that sub-agent token usage is tracked in keypoolStats.
 */
function makeReportSubAgent(
  modelId: string,
  systemPrompt: string,
  providerId: string,
  apiKey: string | undefined,
  keypoolEventHandler?: KeypoolEventHandler,
): Agent {
  return new Agent({
    providerId,
    modelId,
    apiKey,
    systemPrompt,
    tools: [],
    ...(keypoolEventHandler ? { keypoolEventHandler } : {}),
  })
}

/**
 * Returns a backtick fence string long enough to safely wrap `content`.
 * Finds the longest run of consecutive backticks in the content and uses
 * one more, with a minimum of 3.  This prevents inner ``` from closing the
 * outer fence and breaking Markdown rendering.
 */
function safeFence(content: string): string {
  const maxRun = Math.max(0, ...(content.match(/`+/g) ?? []).map((s) => s.length))
  return "`".repeat(Math.max(3, maxRun + 1))
}

/**
 * Calls the fast model to produce a Mermaid flowchart summarising the agent run.
 * Returns a fenced mermaid code block string, or a fallback placeholder on error.
 *
 * @param config     - Validated `SyncConfig` — used for `models.fast` and `models.provider`.
 * @param runSummary - Compact plain-text description of the completed run.
 * @param providerId - Provider identifier forwarded to the sub-agent.
 * @param apiKey     - API key forwarded to the sub-agent.
 */
async function generateMermaidDiagram(
  config: SyncConfig,
  runSummary: string,
  providerId: string,
  apiKey: string | undefined,
  keypoolEventHandler?: KeypoolEventHandler,
): Promise<string> {
  const systemPrompt = `You are a technical diagram generator. When given a summary of a Git backport agent run, \
produce a single Mermaid flowchart (flowchart TD) that visually represents: \
(1) each candidate commit as a node labelled with its short SHA and subject, \
(2) the risk level applied to each commit (low / medium / high), \
(3) which AI tools were invoked (analyze_commit_for_backport, check_customization_compatibility, resolve_conflict_with_ai), \
(4) the final disposition of each commit (applied ✅, blocked ⛔, needs-review ⚠️, skipped ⟳). \
Use colour-coded styles: applied=green, blocked=red, needs-review=orange, skipped=grey. \
\
IMPORTANT: Always wrap node labels containing parentheses, brackets, or other special Mermaid characters in double quotes. \
For example: "commit123(feat: add feature)" instead of commit123(feat: add feature). \
Output ONLY the raw Mermaid code, no prose, no code fence.`

  const userPrompt = `Agent run summary:\n\n${runSummary}\n\nOutput the Mermaid flowchart now.`

  try {
    const subAgent = makeReportSubAgent(config.models.fast, systemPrompt, providerId, apiKey, keypoolEventHandler)
    const result = await subAgent.run(userPrompt)
    const raw = (result.outputText ?? "").trim()
    // Strip any accidental code fence if the model added one.
    const inner = raw.replace(/^```(?:mermaid)?\n?/i, "").replace(/\n?```$/, "").trim()
    return "```mermaid\n" + inner + "\n```"
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err)
    return `<!-- Mermaid generation failed: ${msg} -->`
  }
}

// ---------------------------------------------------------------------------
// Zod schemas
// ---------------------------------------------------------------------------

/**
 * Zod schema for the result of processing a single upstream commit.
 *
 * The agent populates one `CommitResult` per candidate commit processed during
 * the run.  These are aggregated by the report tool to produce the final summary.
 */
const CommitResultSchema = z.object({
  /** Full SHA of the upstream commit. */
  sha: z.string(),
  /** Commit subject line (first line of the message). */
  subject: z.string(),
  /** Risk level assigned by `classify_commit_risk`. */
  riskLevel: z.enum(["low", "medium", "high"]),
  /**
   * Final disposition of this commit:
   *  - `"applied"`           — cherry-picked cleanly with no conflicts.
   *  - `"skipped"`           — already applied in the fork (git cherry found equivalent patch).
   *  - `"conflict-resolved"` — had conflicts that the agent resolved automatically.
   *  - `"conflict-blocked"`  — had conflicts the agent could not safely resolve; needs human review.
   *  - `"validation-failed"` — cherry-picked cleanly but the validation suite failed.
   */
  status: z.enum(["applied", "skipped", "conflict-resolved", "conflict-blocked", "validation-failed"]),
  /** Paths of files that had merge conflicts (populated for conflict-* statuses). */
  conflictedFiles: z.array(z.string()).optional(),
  /** Human-readable reasons why this commit needs manual review. */
  humanReviewReasons: z.array(z.string()).optional(),
  /** Per-command validation results, populated when `status === "validation-failed"`. */
  validationResults: z.array(z.object({ command: z.string(), success: z.boolean(), output: z.string() })).optional(),
})

/**
 * TypeScript type for a single commit result, inferred from `CommitResultSchema`.
 */
export type CommitResult = z.infer<typeof CommitResultSchema>

// ---------------------------------------------------------------------------
// Factory
// ---------------------------------------------------------------------------

/**
 * Builds and returns the `generate_report` agent tool.
 *
 * @param config        - Validated `SyncConfig` — used for model IDs and `report.destination`.
 * @param promptLogPath - Absolute path to the JSONL file written by `logPrompt()` in ai-tools.ts.
 * @param providerId    - Provider identifier used to instantiate sub-agents (e.g. `"openai"`).
 * @param apiKey        - Resolved API key for the provider, or `undefined` if env-based.
 * @returns A single agent tool: `generate_report` (with `completesRun: true`).
 */
export function makeReportTool(
  config: SyncConfig,
  promptLogPath: string,
  providerId: string,
  apiKey: string | undefined,
  keypoolEventHandler?: KeypoolEventHandler,
  runState?: RunState,
) {
  return defineTool({
    name: "generate_report",
    description:
      "Generate the final sync report as a Markdown string suitable for a PR body. " +
      "Call this as the LAST step after all commits have been processed. " +
      "Returns the report text AND signals that the agent run is complete.",
    inputSchema: z.object({
      /** Name of the sync branch, or `null` in dry-run mode. */
      syncBranch: z.string().nullable(),
      /** Full ref of the upstream branch, e.g. `"upstream/main"`. */
      upstreamRef: z.string(),
      /** Full ref of the fork branch, e.g. `"origin/main"`. */
      forkRef: z.string(),
      /** Array of per-commit results — one entry per processed candidate. */
      commitResults: z.array(CommitResultSchema),
      /** Commits that were not attempted at all, with mandatory reasons. */
      blockedCommits: z.array(z.object({
        /** Full or abbreviated SHA of the blocked commit. */
        sha: z.string(),
        /** Human-readable reason why this commit was not attempted. */
        reason: z.string().describe("Why this commit was not attempted (AI analysis result, policy, etc.)"),
        /** Risk level from classify_commit_risk, if known. */
        riskLevel: z.enum(["low", "medium", "high"]).optional(),
      })).describe("Commits not attempted, each with a specific reason"),
      /**
       * All SHAs returned by list_candidate_commits — used to detect silently dropped commits.
       * Pass the complete list so the report can cross-check accountability.
       */
      allCandidateShas: z.array(z.string()).optional().describe(
        "Complete list of SHAs from list_candidate_commits, used to detect unaccounted commits"
      ),
      /** Ordered list of key decisions the agent made during this run, for audit purposes. */
      agentDecisions: z.array(z.string()).describe("Audit trail of key decisions made during this run"),
    }),
    // completesRun:true tells the SDK to stop the agent loop after this tool returns.
    lifecycle: { completesRun: true },
    execute: async ({ syncBranch, upstreamRef, forkRef, commitResults, blockedCommits, agentDecisions, allCandidateShas }) => {
      // Remove the within-run checkpoint — the run completed successfully.
      try {
        const checkpointPath = joinPath(config.workingDir, CHECKPOINT_FILENAME)
        if (existsSync(checkpointPath)) unlinkSync(checkpointPath)
      } catch {
        // Non-fatal — checkpoint cleanup failure must not prevent report generation.
      }

      const date = new Date().toISOString()
      const timestampSlug = date.replace(/[:.]/g, "-").replace("T", "_").slice(0, 19)

      // --- Partition commits by final status for the summary section ---
      const applied = commitResults.filter((r) => ["applied", "conflict-resolved"].includes(r.status))
      const needsReview = commitResults.filter((r) => ["conflict-blocked", "validation-failed"].includes(r.status))

      // --- Host-side reconciliation against the run state ---
      // The model may under-report problems (observed in real runs: a failed
      // validation suite reported as a clean sync).  A run with a failed
      // validation or any host-gate activation can never be presented as clean.
      const hostValidationFailed = runState ? validationFailed(runState) : false
      // Observed in a real run: a commit was cherry-picked and applied while
      // run_validation was never called at all (0 validation records), which
      // validationFailed() cannot distinguish from "validation ran and passed"
      // since .some() on an empty array is false. Applying any commit without
      // ever validating is the same blind spot as a failed validation.
      const hostValidationSkippedWithAppliedCommits =
        runState != null && applied.length > 0 && !validationRan(runState)
      const hostGateEvents = runState?.gateEvents ?? []
      const allPassed =
        needsReview.length === 0 && !hostValidationFailed && !hostValidationSkippedWithAppliedCommits
      const needsHumanReview =
        needsReview.length > 0 ||
        hostValidationFailed ||
        hostValidationSkippedWithAppliedCommits ||
        hostGateEvents.length > 0

      // --- Accountability check: detect silently dropped commits ---
      const processedShas = new Set([
        ...commitResults.map((r) => r.sha),
        ...blockedCommits.map((c) => c.sha),
      ])
      const unaccounted = (allCandidateShas ?? []).filter(
        (sha) => !processedShas.has(sha) && !processedShas.has(sha.slice(0, 8))
      )

      // --- Build the PR-body Markdown line by line ---
      const prBodyLines: string[] = [
        "## Backport Agent — Sync Report",
        "",
        `**Date**: ${date}`,
        `**Upstream ref**: \`${upstreamRef}\``,
        `**Cut date**: ${config.upstream.cutDate ? `\`${config.upstream.cutDate}\`` : "_none (all commits considered)_"} `,
        `**Fork ref**: \`${forkRef}\``,
        `**Sync branch**: ${syncBranch ? `\`${syncBranch}\`` : "_dry-run (no branch created)_"}`,
        "",
        "### Summary",
        "",
        `- ✅ Applied: ${applied.length}`,
        `- ⚠️ Needs human review: ${needsReview.length}`,
        `- ⛔ Blocked (not attempted): ${blockedCommits.length}`,
        ...(unaccounted.length > 0 ? [`- 🔴 Unaccounted (agent bug): ${unaccounted.length}`] : []),
        ...(hostValidationFailed ? ["- 🔴 Validation suite FAILED during this run (host-verified)"] : []),
        ...(hostValidationSkippedWithAppliedCommits
          ? ["- 🔴 Commits were applied but run_validation was never called during this run (host-verified)"]
          : []),
        "",
      ]

      if (hostValidationFailed || hostValidationSkippedWithAppliedCommits || hostGateEvents.length > 0) {
        prBodyLines.push("### 🛑 Host-side gate report", "")
        if (hostValidationFailed) {
          const failedLevels = (runState?.validations ?? []).filter((v) => !v.allPassed).map((v) => v.level)
          prBodyLines.push(
            `- Validation suite(s) FAILED: ${failedLevels.join(", ")} — this run requires human review ` +
              "regardless of per-commit statuses above.",
          )
        }
        if (hostValidationSkippedWithAppliedCommits) {
          prBodyLines.push(
            `- ${applied.length} commit(s) were applied but run_validation was never invoked — this run ` +
              "requires human review regardless of per-commit statuses above.",
          )
        }
        for (const event of hostGateEvents) prBodyLines.push(`- ${event}`)
        prBodyLines.push("")
      }

      if (applied.length > 0) {
        prBodyLines.push("### Applied commits", "")
        for (const r of applied) {
          const badge = r.status === "conflict-resolved" ? " _(conflict resolved by agent)_" : ""
          prBodyLines.push(`- \`${r.sha.slice(0, 8)}\` [${r.riskLevel}] ${r.subject}${badge}`)
        }
        prBodyLines.push("")
      }

      if (needsReview.length > 0) {
        prBodyLines.push("### ⚠️ Human review required", "")
        for (const r of needsReview) {
          prBodyLines.push(`- \`${r.sha.slice(0, 8)}\` ${r.subject}`)
          if (r.conflictedFiles?.length) prBodyLines.push(`  - Conflicted files: ${r.conflictedFiles.join(", ")}`)
          if (r.humanReviewReasons?.length) {
            for (const reason of r.humanReviewReasons) prBodyLines.push(`  - ${reason}`)
          }
        }
        prBodyLines.push("")
      }

      if (blockedCommits.length > 0) {
        prBodyLines.push("### Blocked commits (not attempted)", "")
        for (const { sha, reason, riskLevel } of blockedCommits) {
          const badge = riskLevel ? ` [${riskLevel}]` : ""
          prBodyLines.push(`- \`${sha.slice(0, 8)}\`${badge} — ${reason}`)
        }
        prBodyLines.push("")
      }

      if (unaccounted.length > 0) {
        prBodyLines.push("### 🔴 Unaccounted commits (agent processing gap)", "")
        for (const sha of unaccounted) prBodyLines.push(`- \`${sha.slice(0, 8)}\` — not processed or reported by agent`)
        prBodyLines.push("")
      }

      if (agentDecisions.length > 0) {
        prBodyLines.push("### Agent decision log", "")
        for (const decision of agentDecisions) prBodyLines.push(`- ${decision}`)
        prBodyLines.push("")
      }

      const report = prBodyLines.join("\n")

      // --- Build the machine-readable state object for idempotent re-runs ---
      const agentState = {
        generatedAt: date,
        appliedShas: applied.map((r) => r.sha),
        blockedShas: blockedCommits.map((c) => c.sha),
        needsReviewShas: needsReview.map((r) => r.sha),
        unaccountedShas: unaccounted,
      }

      // -----------------------------------------------------------------------
      // Detailed report file — combines PR body, Mermaid diagram, and AI call log
      // -----------------------------------------------------------------------

      // Build a compact plain-text run summary for the Mermaid prompt.
      const runSummaryForDiagram = [
        `Upstream: ${upstreamRef}  Fork: ${forkRef}`,
        `Applied (${applied.length}): ${applied.map((r) => `${r.sha.slice(0, 8)} [${r.riskLevel}] ${r.subject}`).join(" | ") || "none"}`,
        `Blocked (${blockedCommits.length}): ${blockedCommits.map((c) => `${c.sha.slice(0, 8)} — ${c.reason}`).join(" | ") || "none"}`,
        `Needs review (${needsReview.length}): ${needsReview.map((r) => r.sha.slice(0, 8)).join(", ") || "none"}`,
        `AI calls: ${readPromptLog(promptLogPath).prompts.map((e) => `${e.tool}(${e.model}, ${e.durationMs}ms)`).join(", ") || "none"}`,
      ].join("\n")

      const mermaidBlock = await generateMermaidDiagram(config, runSummaryForDiagram, providerId, apiKey, keypoolEventHandler)

      // Read and format the prompt log entries.
      const { prompts: promptEntries, auditEvents } = readPromptLog(promptLogPath)

      const detailedLines: string[] = [
        "# Backport Agent — Detailed Run Report",
        "",
        "> This file is generated automatically. It is intended for human analysts and",
        "> AI reasoning models to assess agent performance, decision quality, and LLM behavior.",
        "",
        `**Run timestamp**: ${date}`,
        `**Models used**: fast=\`${config.models.fast}\`  powerful=\`${config.models.powerful}\``,
        `**Prompt log**: \`${promptLogPath}\``,
        "",
        "---",
        "",
        "## Summary (PR body)",
        "",
        report,
        "",
        "---",
        "",
        "## Agent Workflow Diagram",
        "",
        "> Generated by the fast model from the run summary. Evaluate the agent's decision path.",
        "",
        mermaidBlock,
        "",
        "---",
        "",
        `## AI Sub-Agent Call Log (${promptEntries.length} call${promptEntries.length === 1 ? "" : "s"})`,
        "",
        "> Each entry is one sub-agent invocation. Review prompt/response pairs to assess",
        "> reasoning quality, hallucinations, and decision accuracy.",
        "",
      ]

      for (let i = 0; i < promptEntries.length; i++) {
        const e = promptEntries[i]
        const statusBadge = e.error ? "❌ Error" : "✅ OK"
        detailedLines.push(
          `### Call ${i + 1} / ${promptEntries.length} — \`${e.tool}\` ${statusBadge}`,
          "",
          `| Field | Value |`,
          `|---|---|`,
          `| **Timestamp** | ${e.timestamp} |`,
          `| **Tool** | \`${e.tool}\` |`,
          `| **Model** | \`${e.model}\` |`,
          `| **Duration** | ${e.durationMs} ms |`,
          ...(e.inputTokens != null ? [`| **Tokens in** | ${e.inputTokens} |`] : []),
          ...(e.outputTokens != null ? [`| **Tokens out** | ${e.outputTokens} |`] : []),
          ...(e.cacheReadTokens != null && e.cacheReadTokens > 0 ? [`| **Cache read** | ${e.cacheReadTokens} |`] : []),
          ...(e.cacheWriteTokens != null && e.cacheWriteTokens > 0 ? [`| **Cache write** | ${e.cacheWriteTokens} |`] : []),
          ...(e.totalCost != null ? [`| **Cost** | $${e.totalCost.toFixed(6)} |`] : []),
          ...(e.error ? [`| **Error** | ${e.error} |`] : []),
          "",
          "**Prompt sent to sub-agent:**",
          "",
          safeFence(e.prompt),
          e.prompt,
          safeFence(e.prompt),
          "",
          "**Response received:**",
          "",
          safeFence(e.response || "(empty)"),
          e.response || "(empty)",
          safeFence(e.response || "(empty)"),
          "",
          "---",
          "",
        )
      }

      if (promptEntries.length === 0) {
        detailedLines.push("_No AI sub-agent calls were made during this run._", "", "---", "")
      }

      // Performance summary table.
      if (promptEntries.length > 0) {
        const totalMs = promptEntries.reduce((sum, e) => sum + e.durationMs, 0)
        const totalIn = promptEntries.reduce((sum, e) => sum + (e.inputTokens ?? 0), 0)
        const totalOut = promptEntries.reduce((sum, e) => sum + (e.outputTokens ?? 0), 0)
        const totalCost = promptEntries.reduce((sum, e) => sum + (e.totalCost ?? 0), 0)
        const byTool = new Map<string, { count: number; totalMs: number; totalIn: number; totalOut: number }>()
        for (const e of promptEntries) {
          const cur = byTool.get(e.tool) ?? { count: 0, totalMs: 0, totalIn: 0, totalOut: 0 }
          byTool.set(e.tool, {
            count: cur.count + 1,
            totalMs: cur.totalMs + e.durationMs,
            totalIn: cur.totalIn + (e.inputTokens ?? 0),
            totalOut: cur.totalOut + (e.outputTokens ?? 0),
          })
        }
        const hasTokenData = totalIn > 0 || totalOut > 0
        detailedLines.push(
          "## Performance Summary",
          "",
          `**Total AI time**: ${totalMs} ms across ${promptEntries.length} call(s)`,
          ...(hasTokenData ? [
            `**Total input tokens**: ${totalIn}`,
            `**Total output tokens**: ${totalOut}`,
            ...(totalCost > 0 ? [`**Total estimated cost**: $${totalCost.toFixed(6)}`] : []),
          ] : []),
          "",
          hasTokenData
            ? "| Tool | Calls | Total ms | Avg ms | Input tok | Output tok |"
            : "| Tool | Calls | Total ms | Avg ms |",
          hasTokenData ? "|---|---|---|---|---|---|" : "|---|---|---|---|",
          ...[...byTool.entries()].map(
            ([tool, s]) => hasTokenData
              ? `| \`${tool}\` | ${s.count} | ${s.totalMs} | ${Math.round(s.totalMs / s.count)} | ${s.totalIn} | ${s.totalOut} |`
              : `| \`${tool}\` | ${s.count} | ${s.totalMs} | ${Math.round(s.totalMs / s.count)} |`,
          ),
          "",
        )
      }

      // -----------------------------------------------------------------------
      // Decision Quality Metrics section (Improvement 7)
      // -----------------------------------------------------------------------
      {
        // Conflict resolution confidence distribution.
        const conflictCalls = promptEntries.filter((e) => e.tool === "resolve_conflict_with_ai")
        const guardedCalls = conflictCalls.filter((e) => e.guards && (e.guards as string[]).length > 0)
        const markerCalls = conflictCalls.filter((e) => e.hasConflictMarkers)
        const syntaxFailCalls = conflictCalls.filter((e) => e.syntaxValid === false)
        const consensusFailCalls = conflictCalls.filter((e) => e.consensusFailure === true)
        const confidenceDist = { high: 0, medium: 0, low: 0 }
        for (const e of conflictCalls) {
          const c = (e.effectiveConfidence ?? e.originalConfidence ?? "unknown") as string
          if (c === "high" || c === "medium" || c === "low") confidenceDist[c]++
        }

        // Hallucination suspects across analyze calls.
        const analyzeCalls = promptEntries.filter((e) => e.tool === "analyze_commit_for_backport")
        const totalHallucinationSuspects = analyzeCalls.reduce(
          (sum, e) => sum + (e.hallucinationSuspectsCount ?? 0),
          0,
        )

        // Contradiction events from reconcile_ai_assessments audit log.
        const contradictionEvents = auditEvents.filter(
          (e) => e.tool === "reconcile_ai_assessments" && e.event === "contradiction_detected",
        )

        // Compatibility calls enriched with file context.
        const compatCalls = promptEntries.filter((e) => e.tool === "check_customization_compatibility")
        const enrichedCompatCalls = compatCalls.filter((e) => e.fileContentEnriched === true)
        const incompatibleCalls = compatCalls.filter((e) => e.compatible === false)

        detailedLines.push(
          "## Decision Quality Metrics",
          "",
          "> Automated quality signals derived from tool output guards, schema validation,",
          "> hallucination detection, and consensus checks.  Review flagged items manually.",
          "",
        )

        if (conflictCalls.length > 0) {
          detailedLines.push(
            "### Conflict Resolution Quality",
            "",
            `| Metric | Value |`,
            `|---|---|`,
            `| Total conflict resolutions | ${conflictCalls.length} |`,
            `| Confidence: high / medium / low | ${confidenceDist.high} / ${confidenceDist.medium} / ${confidenceDist.low} |`,
            `| Conflict markers detected (guard triggered) | ${markerCalls.length} |`,
            `| Syntax balance failures | ${syntaxFailCalls.length} |`,
            `| Consensus divergences (if enabled) | ${consensusFailCalls.length} |`,
            `| Total guard activations | ${guardedCalls.length} |`,
            "",
          )
          if (guardedCalls.length > 0) {
            detailedLines.push("**Guard details:**", "")
            for (const e of guardedCalls) {
              detailedLines.push(`- \`${e.tool}\` — guards: ${(e.guards as string[]).join(", ")}`)
            }
            detailedLines.push("")
          }
        }

        if (analyzeCalls.length > 0) {
          detailedLines.push(
            "### Commit Analysis Quality",
            "",
            `| Metric | Value |`,
            `|---|---|`,
            `| Total analyze calls | ${analyzeCalls.length} |`,
            `| Commits with semantic risk factors | ${analyzeCalls.filter((e) => (e.semanticRiskFactorsCount ?? 0) > 0).length} |`,
            `| Possible hallucinated references (total) | ${totalHallucinationSuspects} |`,
            "",
          )
        }

        if (compatCalls.length > 0) {
          detailedLines.push(
            "### Compatibility Check Quality",
            "",
            `| Metric | Value |`,
            `|---|---|`,
            `| Total compatibility checks | ${compatCalls.length} |`,
            `| Checks with file content enrichment | ${enrichedCompatCalls.length} |`,
            `| Incompatible results | ${incompatibleCalls.length} |`,
            "",
          )
        }

        if (contradictionEvents.length > 0) {
          detailedLines.push(
            "### ⚠️ AI Assessment Contradictions",
            "",
            `> ${contradictionEvents.length} contradiction(s) were detected by \`reconcile_ai_assessments\`.`,
            "> These are cases where analyze_commit recommended apply but check_customization found issues.",
            "",
          )
          for (const ev of contradictionEvents) {
            const d = ev.details ?? {}
            detailedLines.push(
              `- **SHA**: \`${String(d.sha ?? "?").slice(0, 8)}\`  analyze=\`${d.analyzeRecommendation ?? "?"}\`  ` +
                `compatible=\`${d.compatibilityCompatible ?? "?"}\`  final=\`${d.finalRecommendation ?? "?"}\``,
            )
          }
          detailedLines.push("")
        }

        if (auditEvents.length > 0) {
          detailedLines.push(
            "### Audit Event Timeline",
            "",
            `| Timestamp | Tool | Event | Details |`,
            `|---|---|---|---|`,
            ...auditEvents.map((ev) => {
              const detailStr = ev.details
                ? Object.entries(ev.details)
                    .slice(0, 3)
                    .map(([k, v]) => `${k}=${JSON.stringify(v).slice(0, 40)}`)
                    .join(", ")
                : ""
              return `| ${ev.timestamp.slice(11, 19)} | \`${ev.tool}\` | \`${ev.event}\` | ${detailStr} |`
            }),
            "",
          )
        }
      }

      // Write the detailed report to disk (skipped in dry-run mode).
      if (config.sync.dryRun) {
        process.stderr.write("[Report] Dry-run mode — detailed report not written to disk.\n")
      } else {
        try {
          const destDir = resolvePath(config.workingDir, config.report.destination)
          mkdirSync(destDir, { recursive: true })
          const reportFilename = `report.${timestampSlug}.md`
          const reportFilePath = joinPath(destDir, reportFilename)
          writeFileSync(reportFilePath, detailedLines.join("\n"), "utf8")
          process.stderr.write(`[Report] Detailed report written to: ${reportFilePath}\n`)

          // Commit and push the report file to the sync branch if inside the repo.
          const relPath = relativePath(config.workingDir, reportFilePath)
          if (syncBranch && !relPath.startsWith("..")) {
            git(["add", relPath], config.workingDir)
            git(["commit", "-m", `chore(backport): add run report ${reportFilename}`], config.workingDir)
            git(["push", config.fork.remote, syncBranch], config.workingDir)
            process.stderr.write(`[Report] Report committed and pushed to ${config.fork.remote}/${syncBranch}\n`)
          }
        } catch (err) {
          const msg = err instanceof Error ? err.message : String(err)
          process.stderr.write(`[Report] Warning: could not write/commit detailed report: ${msg}\n`)
        }
      }

      // --- Deterministic PR creation (wires config.sync.createPullRequest) ---
      // Because generate_report completes the run, any prompt step after it never
      // executes — so the PR must be created here, host-side, not by the model.
      let pr: { url: string; number: number; created: boolean } | null = null
      if (config.sync.createPullRequest && syncBranch && !config.sync.dryRun) {
        try {
          pr = await createOrUpdateSyncPr(config, syncBranch, report, agentState)
          process.stderr.write(
            `[Report] Sync PR ${pr.created ? "created" : "updated"}: ${pr.url}\n`,
          )
        } catch (err) {
          const msg = err instanceof Error ? err.message : String(err)
          process.stderr.write(`[Report] Warning: could not create/update sync PR: ${msg}\n`)
        }
      }

      // Record the outcome for main.ts exit-code mapping.
      if (runState) {
        runState.reportOutcome = {
          allPassed,
          needsHumanReview,
          blockedCount: blockedCommits.length,
          unaccountedCount: unaccounted.length,
        }
      }

      return { report, agentState, allPassed, needsHumanReview, pr }
    },
  })
}

